---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - settings.github.com
  resources:
  - inviteusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - settings.github.com
  resources:
  - inviteusers/finalizers
  verbs:
  - update
- apiGroups:
  - settings.github.com
  resources:
  - inviteusers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - settings.github.com
  resources:
  - repositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - settings.github.com
  resources:
  - repositories/finalizers
  verbs:
  - update
- apiGroups:
  - settings.github.com
  resources:
  - repositories/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - settings.github.com
  resources:
  - teams
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - settings.github.com
  resources:
  - teams/finalizers
  verbs:
  - update
- apiGroups:
  - settings.github.com
  resources:
  - teams/status
  verbs:
  - get
  - patch
  - update
