# permissions for end users to view globalrepositories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: globalrepository-viewer-role
rules:
- apiGroups:
  - settings.github.com
  resources:
  - globalrepositories
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - settings.github.com
  resources:
  - globalrepositories/status
  verbs:
  - get
