# permissions for end users to view teams.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: team-viewer-role
rules:
- apiGroups:
  - settings.github.com
  resources:
  - teams
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - settings.github.com
  resources:
  - teams/status
  verbs:
  - get
