# permissions for end users to edit globalrepositories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: globalrepository-editor-role
rules:
- apiGroups:
  - settings.github.com
  resources:
  - globalrepositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - settings.github.com
  resources:
  - globalrepositories/status
  verbs:
  - get
