# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/settings.github.com_repositories.yaml
- bases/settings.github.com_teams.yaml
- bases/settings.github.com_inviteusers.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_repositories.yaml
#- patches/webhook_in_teams.yaml
#- patches/webhook_in_collaborators.yaml
#- patches/webhook_in_inviteusers.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_repositories.yaml
#- patches/cainjection_in_teams.yaml
#- patches/cainjection_in_collaborators.yaml
#- patches/cainjection_in_inviteusers.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
